name-template: '$RELEASE_VERSION'
tag-template: '$RELEASE_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feat'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
  - title: 'ğŸ§¹ Chores'
    labels:
      - 'chore'
  - title: 'ğŸ“š Documentation'
    labels:
      - 'docs'
  - title: 'ğŸ’… Styles'
    labels:
      - 'style'
  - title: 'â™»ï¸ Refactoring'
    labels:
      - 'refactor'
  - title: 'âš¡ï¸ Performance'
    labels:
      - 'perf'
  - title: 'ğŸ§ª Tests'
    labels:
      - 'test'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to everyone who contributed to this release:
  $CONTRIBUTORS
